ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
ENV LANG=C.UTF-8 \
    TERM=screen-256color
#
RUN set -xe \
#     && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && apk add --no-cache --purge -uU curl weechat ca-certificates tzdata unzip weechat-perl weechat-python \
    && pip install --no-cache six websocket-client \
    && rm -rf /var/cache/apk/* /tmp/*
#
# COPY root/ /
#
USER alpine
WORKDIR /home/alpine/
VOLUME /home/alpine/
#
EXPOSE 9001
#
ENTRYPOINT ["weechat"]
