#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

# ensure conf dirs
vecho "Ensure configuration directories exist.";
if [ -z "${WEECHAT_HOME}" ];
then
    S6_USERHOME="${S6_USERHOME:-$(getent passwd ${S6_USER:-alpine} | cut -d: -f6)}";
    mkdir -p \
        "${S6_USERHOME}/.cache/weechat" \
        "${S6_USERHOME}/.config/weechat" \
        "${S6_USERHOME}/.local/share/weechat" \
        "${S6_USERHOME}/.local/state/weechat" \
        "${S6_USERHOME}/.weechat" \
        ;
else
    mkdir -p "${WEECHAT_HOME}";
fi;

# fix permissions
if [ -z "${WEECHAT_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    if [ -z "${WEECHAT_HOME}" ];
    then
        chown ${S6_USER:-alpine}:${PGID:-1000} \
            "${S6_USERHOME}" \
            ;

        chown -R ${S6_USER:-alpine}:${PGID:-1000} \
            "${S6_USERHOME}/.cache/weechat" \
            "${S6_USERHOME}/.config/weechat" \
            "${S6_USERHOME}/.local/share/weechat" \
            "${S6_USERHOME}/.local/state/weechat" \
            "${S6_USERHOME}/.weechat" \
        ;
    else
        chown -R ${S6_USER:-alpine}:${PGID:-1000} \
            "${WEECHAT_HOME}" \
            ;
    fi;
fi;
